### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by AnaeyGuillen** [Jannape/lim-2018-05-bc-core-am-datadashboard#10]
El tiempo límite de nuestro proyecto fue de **3 sprints**, los cuales distribuimos el tiempo con pequeñas tareas para poder completar una buena presentación en cada uno de los Demos. Nos ayudó mucho separar nuestro Readme enfocándonos en la experiencia de usuario que queríamos alcanzar, además adjuntamos fotos de los logros durante estos sprints.

**Comment by Jannape** [comment]
La explicación de todo el proyecto por fases de los sprints ayudó en el uso del tiempo.
