### ISSUE TITLE
Manipular la data

### ISSUE THREAD

**Issue by AnaeyGuillen** [Jannape/lim-2018-05-bc-core-am-datadashboard#11]
Dentro de los requerimientos primordiales del proyecto **Datadasboard** es manipular la data que nos han brindado, como es el caso de archivos _Json_ los cuales debiamos aprender a llamarlos puesto que para este proyecto aprendimos lo que son el uso de _Arrays_ y _Objects._
Información básica a la que podíamos acceder a través de nuestro portal en el **LMS de Laboratoria** ya que podíamos practicar con los ejercicios propuestos y resolver quizzes para medir la capacidad de comprensión del tema.

**Comment by Jannape** [comment]
Parte fundamental de la funcionalidad cumplida.
