### ISSUE TITLE
Uso de prueba y error - console.log()

### ISSUE THREAD

**Issue by AnaeyGuillen** [Jannape/lim-2018-05-bc-core-am-datadashboard#12]
Parte fundamental de programar es poder descubrir cuando tenemos errores en nuestras líneas de código, para encontrar el error dentro del código que avancemos debemos hacer uso de los prueba-error como es el caso de **console.log()** que nos ayuda a mostrar el resultado de lo que nuestra función pide y saber si va bien encaminada.

**Comment by Jannape** [comment]
Con la ayuda del uso de console.log() se logró descubrir errores en el código.
