### ISSUE TITLE
User Centricity

### ISSUE THREAD

**Issue by Jannape** [Jannape/lim-2018-05-bc-core-am-datadashboard#4]
Se pidió al usuario interactuar   con la aplicación en desarrollo.
Se pudo rescatar lo sgt a modo de FeedBack
El usuario considero que se filtrara los cohorts solo de Lima.Pues no era práctico para el usuario visualizar cohorts de otras sedes que no sea su sede.

El usuario considero que la manera de mostrar el lugar donde va cada elemento es amigable para él.
Resalto la importancia de  tomar en cuenta los colores y logos de la organización.

**Comment by Jannape** [comment]
Se espera  que  se ordené por nombre,  se agregaron botones a las cabeceras de las tablas , se usa etiquetas button con transparencia, esperando  ordenar al hacer clic en la cabecera  de la tabla correspondiente.. (pendiente)

**Comment by AnaeyGuillen** [comment]
En base a los requerimientos de la **Training Manager** se procedió a estructurar de una manera más visual y amigable la vista que apreciará durante su uso, con cortos pasos de acceso a la información. Usando para ello estilos de acuerdo al logo, tipografía y colores predeterminados por la institución.
