### ISSUE TITLE
Primer prototipo

### ISSUE THREAD

**Issue by AnaeyGuillen** [Jannape/lim-2018-05-bc-core-am-datadashboard#7]
En base al **primer sprint** teníamos en claro que lo que debemos plasmar en nuestra página es la experiencia de usuario además de la funcionalidad, por lo tanto al iniciar el proyecto se plasmó un prototipo básico con lo que habíamos imaginado sería útil a nuestra Training Manager, y procedimos con una entrevista en base a ese prototipo de baja fidelidad como se muestra con imágenes en el readme. Después de la entrevista se concluyó las mejoras que teníamos que implementar y trabajar en ello. Pues nuestro siguiente paso era plasmarlo en un prototipo de alta fidelidad.

**Comment by Jannape** [comment]
Se cumplió con las expectativas iniciales de backlog
